# v2.5.1. Created based on golangci-lint v2.5.0
version: "2"

run:
  relative-path-mode: gomod
  modules-download-mode: readonly
  allow-serial-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  # fix: true

severity:
  default: error

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    gci:
      sections:
        - standard
        - localmodule
        - default
        - blank
        - dot
        # - alias
      custom-order: true
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
    gofumpt:
      extra-rules: true
  exclusions:
    generated: strict

linters:
  enable:
    # - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    # - cyclop
    - decorder
    - depguard
    - dogsled
    # - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    # - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    # - gocognit
    - goconst
    - gocritic
    # - gocyclo
    # - godoclint
    # - godot
    - godox
    # - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    # - importas
    - inamedparam
    - ineffassign
    # - interfacebloat
    - intrange
    - iotamixing
    # - ireturn
    # - lll
    - loggercheck
    # - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    # - nlreturn
    - noctx
    # - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    # - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    # - wsl
    # - wsl_v5
    - zerologlint
  settings:
    asasalint:
      use-builtin-exclusions: false
    copyloopvar:
      check-alias: true
    decorder:
      disable-init-func-first-check: false
    depguard:
      rules:
        all:
          list-mode: lax
          deny:
            - pkg: flag
              desc: "`flag` package is only allowed in main.go"
            - pkg: io/ioutil
              desc: "`io/ioutil` package is deprecated, use the `io` and `os` package instead"
            - pkg: log$
              desc: "logging is provided by `log/slog`"
            - pkg: math/rand$
              desc: "use `math/rand/v2` instead"
            - pkg: reflect
              desc: "`reflect` package is dangerous to use"
            - pkg: unsafe
              desc: "`unsafe` package is dangerous to use"
            - pkg: golang.org/x/crypto/ed25519
              desc: "now part of the stdlib, use `crypto/ed25519` instead"
            - pkg: golang.org/x/crypto/hkdf
              desc: "now part of the stdlib, use `crypto/hkdf` instead"
            - pkg: golang.org/x/crypto/pbkdf2
              desc: "now part of the stdlib, use `crypto/pbkdf2` instead"
            - pkg: golang.org/x/crypto/sha3
              desc: "now part of the stdlib, use `crypto/sha3` instead"
    embeddedstructfieldcheck:
      forbid-mutex: true
    errcheck:
      check-blank: true
      check-type-assertions: true
      disable-default-exclusions: true
      verbose: true
    errchkjson:
      report-no-exported: true
    exhaustive:
      default-signifies-exhaustive: true
    fatcontext:
      check-struct-pointers: true
    forbidigo:
      forbid:
        - pattern: ^panic$
        - pattern: ^print(ln)?$
        - pattern: ^fmt\.Print.*$
        - pattern: ^http\.Default.*$
        - pattern: ^time\.Sleep$
      analyze-types: true
    funcorder:
      struct-method: false
    ginkgolinter:
      force-expect-to: true
      force-tonot: true
    goconst:
      numbers: true
      find-duplicates: true
      eval-const-expressions: true
    gocritic:
      enable-all: true
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
      settings:
        captLocal:
          paramsOnly: false
        elseif:
          skipBalanced: false
        truncateCmp:
          skipArchDependent: false
        underef:
          skipRecvDeref: false
        # NOTE: Set this option to false if other projects rely on this project's code
        unnamedResult:
          checkExported: true
    godox:
      keywords:
        - BUG
        - DEBUG
        - FIXME
    gomoddirectives:
      go-debug-forbidden: true
    gosec:
      config:
        global:
          audit: true
          nosec: true
          show-ignored: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: true
    grouper:
      const-require-grouping: true
      import-require-single-import: true
      import-require-grouping: true
    loggercheck:
      require-string-key: true
      no-printf-like: true
    misspell:
      locale: US
    nakedret:
      max-func-lines: 0
    nilnil:
      only-two: false
      detect-opposite: true
    nolintlint:
      require-explanation: true
      require-specific: true
    nonamedreturns:
      report-error-in-defer: true
    perfsprint:
      err-error: true
    predeclared:
      qualified-name: true
    promlinter:
      strict: true
    reassign:
      patterns:
        - .*
    revive:
      confidence: 0
      severity: error
      enable-all-rules: true
      rules:
        # Provided by mnd linter
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: enforce-repeated-arg-type-style
          arguments:
            - short
        - name: enforce-slice-style
          arguments:
            - make
        - name: exported
          disabled: true
        - name: file-header
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: modifies-parameter
          disabled: true
        - name: nested-structs
          disabled: true
        - name: package-comments
          disabled: true
        - name: optimize-operands-order
          disabled: true
      directives:
        - name: specify-disable-reason
          severity: error
    sloglint:
      attr-only: true
      no-global: all
      context: all
      static-msg: true
      msg-style: lowercased
      key-naming-style: snake
      args-on-sep-lines: true
    staticcheck:
      http-status-code-whitelist: []
      checks:
        - all
        - -ST1000
        - -ST1020
        - -ST1021
        - -ST1022
    tagalign:
      strict: true
    tagliatelle:
      case:
        rules:
          json: snake
    testifylint:
      enable-all: true
    testpackage:
      skip-regexp: ^$
    unparam:
      # NOTE: Set this option to false if other projects rely on this project's code
      check-exported: true
    unused:
      # NOTE: Set this option to true if other projects rely on this project's code
      field-writes-are-uses: false
      # NOTE: Set this option to true if other projects rely on this project's code
      exported-fields-are-used: false
      # TODO: Set to false once https://github.com/dominikh/go-tools/issues/1567 is fixed
      parameters-are-used: true
      local-variables-are-used: false
    usestdlibvars:
      time-date-month: true
      time-month: true
      time-layout: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
    usetesting:
      os-temp-dir: true
      context-background: true
      context-todo: true
  exclusions:
    rules:
      - linters:
          - err113
        text: (?i)do not define dynamic errors, use wrapped static errors instead*
      - linters:
          - govet
        text: declaration of "(ctx|err)" shadows
